export enum RQ {
	LOGGED_IN_USER_QUERY = 'LOGGED_IN_USER_QUERY',
	GET_ALL_POSTS_QUERY = 'GET_ALL_POSTS_QUERY',
	GET_ALL_GROUPS_QUERY = 'GET_ALL_GROUPS_QUERY',
	GET_GROUP_QUERY = 'GET_GROUP_QUERY',
	GET_ALL_NOTIFICATIONS_QUERY = 'GET_ALL_NOTIFICATIONS_QUERY',
}
