export const LOGOUT_USER_INIT = 'LOGOUT_USER_INIT';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';

export const UPDATE_USER_FRIEND_SENT_REQUESTS =
	'UPDATE_USER_FRIEND_SENT_REQUESTS';

export const GET_USER_GROUPS_INIT = 'GET_USER_GROUPS_INIT';
export const GET_USER_GROUPS_SUCCESS = 'GET_USER_GROUPS_SUCCESS';
export const GET_USER_GROUPS_FAILED = 'GET_USER_GROUPS_FAILED';

export const USER_CREATE_NEW_GROUP = 'USER_CREATE_NEW_GROUP';

export const GET_USER_NOTIFICATIONS_INIT = 'GET_USER_NOTIFICATIONS_INIT';
export const GET_USER_NOTIFICATIONS_SUCCESS = 'GET_USER_NOTIFICATIONS_SUCCESS';
export const GET_USER_NOTIFICATIONS_FAILED = 'GET_USER_NOTIFICATIONS_FAILED';

export const ACCEPT_FRIEND_REQUEST_INIT = 'ACCEPT_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS';
export const ACCEPT_FRIEND_REQUEST_FAILED = 'ACCEPT_FRIEND_REQUEST_FAILED';

// Remove notification
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// Mark Notification as read
export const READ_ALL_NOTIFICATIONS_SUCCESS = 'READ_ALL_NOTIFICATIONS_SUCCESS';
export const READ_ALL_NOTIFICATIONS_FAILED = 'READ_ALL_NOTIFICATIONS_FAILED';

// UI

export const SHOW_CREATE_POST = 'SHOW_CREATE_POST';

export const UPDATE_USER_INIT = 'UPDATE_USER_INIT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
